version: '3.8'
services:
  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
  api:
    image: <DOCKERHUB_USERNAME>/todo-api:latest
    environment:
      - MONGO_URI=mongodb://mongo:27017/todos_db
      - PORT=3000
    depends_on:
      - mongo
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

volumes:
  mongo-data: