version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: todo-mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  api:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todos_db
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: npm run dev

volumes:
  mongo-data: