- hosts: servers
  become: true
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: ['apt-transport-https','ca-certificates','curl','software-properties-common']
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install docker
      apt:
        name: ['docker-ce','docker-ce-cli','containerd.io']
        state: present
        update_cache: yes

    - name: Install docker-compose via pip
      apt:
        name: python3-pip
        state: present

    - name: Install docker-compose
      pip:
        name: docker-compose

    - name: Ensure docker service running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create app directory
      file:
        path: /opt/todo-app
        state: directory
        owner: ubuntu

    - name: Upload docker-compose.prod.yml
      copy:
        src: ../docker-compose.prod.yml
        dest: /opt/todo-app/docker-compose.yml

    - name: Pull images and start services
      command: docker-compose -f /opt/todo-app/docker-compose.yml pull

    - name: Bring up the stack
      command: docker-compose -f /opt/todo-app/docker-compose.yml up -d